name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:

      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0

        - name: Package Helm Chart
          run: helm package helm/${{ inputs.artifact-name || github.event.repository.name }} --destination helm-chart

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
                name: ${{ inputs.artifact-name || github.event.repository.name }}-chart-${{ github.event.pull_request.number}}-${{ github.run_number}}
                path: helm-chart
