name: Go CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
        default: 'src'
      
      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-22.04
  
    steps:
     
      - name: Determine PR
        id: pr_tag
        if: startsWith( github.ref, 'refs/pull/' )
        run: echo "pr_tag=0.0.0-PR-${{ github.event.pull_request.number}}-${{ github.run_number}}" >> $GITHUB_OUTPUT
      
      # when pr is merged in other than main branch, add default tag
      - name: Create tag
        id: determine_branch_version
        if: startsWith( github.ref, 'refs/heads/main' ) != true && startsWith( github.ref, 'refs/heads/' ) == true
        run: echo "BRANCH_VERSION=default-${{ github.run_number}}" >> $GITHUB_OUTPUT     

      - name: Set version number
        id: version_number
        run: echo "VERSION_NUMBER=${{ steps.determine_branch_version.outputs.BRANCH_VERSION}}" >> $GITHUB_OUTPUT
      
      - name: Set version number2
        id: version_number2
        run: echo "GITHUB_REF=${{ github.ref }}" >> $GITHUB_OUTPUT
