name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
        default: 'src'
      
      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name : get tag
        id: release_tag 
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: false
            
      - name: Check output3
        run: echo "${{steps.release_tag.outputs.tag }}"  
    