name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
        default: 'src'
      
      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Replace with the desired Go version  

      - name: run lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: ${{ inputs.working-directory || 'src' }}
            
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Replace with the desired Go version

      - name: Cache dependencies
        id: cacheStep
        uses: actions/cache@v2
        with:
          path: |
            ${{ inputs.working-directory || 'src' }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
  
      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        working-directory: ${{ inputs.working-directory || 'src' }}
        run: go mod download
        

      - name: Test
        working-directory: ${{ inputs.working-directory || 'src' }}
        run: |
          echo '1' ${{ inputs.working-directory  ||  'src' }}
          go test -v -cover ./... -json > TestResults-${{ inputs.artifact-name || github.event.repository.name }}.json
       
  Upload-Test-Result:
    name: Upload Test Result
    runs-on: ubuntu-latest
    needs: [ unit-test ]

    steps:
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults-${{ inputs.artifact-name || github.event.repository.name }}
          path: ${{ inputs.working-directory || 'src' }}/TestResults-${{ inputs.artifact-name || github.event.repository.name }}.json        

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ unit-test, lint ]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Replace with the desired Go version

      - name: Cache dependencies
        id: cacheStep
        uses: actions/cache@v2
        with:
          path: |
            ${{ inputs.working-directory || 'src' }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: go mod download

      - name: Build application
        run: 
          go build -o ${{ inputs.artifact-name || github.event.repository.name }}
        working-directory: ${{ inputs.working-directory || 'src' }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.working-directory || 'src' }}
          push: false
          tags: ${{ inputs.artifact-name || github.event.repository.name }}:latest
  
  Upload-Artifact:
    name: Upload Artifact
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name || github.event.repository.name }}
          path: ${{ inputs.working-directory || 'src' }}/${{ inputs.artifact-name || github.event.repository.name }}
 
