name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
        default: 'src'
      
      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x # Replace with the desired Go version  
          cache-dependency-path: src/go.sum

      - name: run lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ inputs.working-directory || 'src' }}
            
  unit-test:
    name: Unit test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x # Replace with the desired Go version 
          cache-dependency-path: src/go.sum
  
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory || 'src' }}
        run: go mod download
        
      - name: Test
        working-directory: ${{ inputs.working-directory || 'src' }}
        run:
          go test -v -cover ./... -json > TestResults-${{ inputs.artifact-name || github.event.repository.name }}.json
       
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults-${{ inputs.artifact-name || github.event.repository.name }}.json
          path: ${{ inputs.working-directory || 'src' }}    

  build:
    name: Build and upload
    runs-on: ubuntu-22.04
    needs: [ unit-test, lint ]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x # Replace with the desired Go version
          cache-dependency-path: src/go.sum

      - name: Install dependencies
        run: go mod download
        working-directory: ${{ inputs.working-directory || 'src' }}

      - name: Build application
        run: 
          go build -o ${{ inputs.artifact-name || github.event.repository.name }}
        working-directory: ${{ inputs.working-directory || 'src' }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name || github.event.repository.name }}
          path: ${{ inputs.working-directory || 'src' }}/${{ inputs.artifact-name || github.event.repository.name }}
