name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
        default: 'src'
      
      artifact-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x # Replace with the desired Go version  test

      - name: run lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ inputs.working-directory || 'src' }}
            
  build:
    name: Build and upload
    runs-on: ubuntu-22.04
    needs: [ lint ]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x # Replace with the desired Go version
          cache-dependency-path: ${{ inputs.working-directory || 'src' }}/go.sum

      - name: Install dependencies
        run: go mod download
        working-directory: ${{ inputs.working-directory || 'src' }}

      - name: Build application
        run: 
          go build -o ${{ inputs.artifact-name || github.event.repository.name }}
        working-directory: ${{ inputs.working-directory || 'src' }}

      - name: Determine PR
        id: pr_tag
        if: startsWith( github.ref, 'refs/pull/' )
        run: echo "pr_tag=0.0.0-PR-${{ github.event.pull_request.number}}-${{ github.run_number}}" >> $GITHUB_OUTPUT
      
      # when pr is merged in other than main branch, add default tag
      - name: Create tag
        id: determine_branch_version
        if: startsWith( github.ref, 'refs/heads/main' ) != true && startsWith( github.ref, 'refs/heads/' ) == true
        run: echo "BRANCH_VERSION=default-${{ github.run_number}}" >> $GITHUB_OUTPUT     

      - name: Set version number
        id: version_number
        run: echo "VERSION_NUMBER=${{ steps.determine_branch_version.outputs.BRANCH_VERSION}}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.working-directory || 'src' }}
          push: false
          tags: ${{ inputs.artifact-name || github.event.repository.name}}:${{steps.build_number.outputs.BUILD_NUMBER }}
        
      